# Generated by Django 3.2.6 on 2021-08-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message_roomname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='roomname',
        ),
    ]
